### ISSUE TITLE
Documentation For Java API

### ISSUE THREAD

**Issue by hrzafer** [bwaldvogel/liblinear-java#16]
Hi,

This is a great library. I've been looking for a lightweight, reliable and commercial friendly Java implementation of LogReg, MaxEnt and SVM for a while and surprisingly it wasn't easy as I thought. Could you provide some Java code examples for the basic usage of the API? I could figure out the following but I wonder if there is more to know.

```java
        Problem problem = Train.readProblem(new File("train.libsvm"), 1);
        Problem testProb = Train.readProblem(new File("test.libsvm"), 1);

        SolverType solver = SolverType.L2R_LR; // -s 0
        double C = 1.5;    // cost of constraints violation
        double eps = 0.01; // stopping criteria

        Parameter parameter = new Parameter(solver, C, eps);
        final Model model = Linear.train(problem, parameter);
        File modelFile = new File("model");
        model.save(modelFile);
        for (int i = 0; i < testProb.x.length; i++) {
            Feature[] instance = testProb.x[i];
            double prediction = Linear.predict(model, instance);
        }
```

**Comment by bwaldvogel** [comment]
The code you posted is a common use case, yes. It’s pretty similar to example on http://liblinear.bwaldvogel.de/

I tried to keep the Java API as close as possible to the C++ version. The original documentation is: https://github.com/bwaldvogel/liblinear-java#library-usage

**Comment by bwaldvogel** [comment]
Closing. Please re-open this issue if you have further questions.
