### ISSUE TITLE
Overload Train.readProblem to take an InputStream instead of File

### ISSUE THREAD

**Issue by hrzafer** [bwaldvogel/liblinear-java#17]
Currently, we have to create a file on the disk to be able to train the model. It would be nice if we could create and pass the dataset in memory.

**Comment by bwaldvogel** [comment]
Done with 604b7067e00c70a12930985434fd93c7d7fd4cf4.

**Comment by bwaldvogel** [comment]
available in version 2.11

**Comment by hrzafer** [comment]
By the way, I want to thank you. This library might have the best LogReg and SVM implementations available for Java.
