### ISSUE TITLE
Different Results With the Same Experiment

### ISSUE THREAD

**Issue by hrzafer** [bwaldvogel/liblinear-java#19]
I get slightly different results by running the same experiment (LogReg L1, reg=0.3) each time. Is that possible or must there be a bug either with the library or with my code?  

This is not the case if I use LogReg L2. I get the exactly same results. I am testing out the other LogReg L1 implementations (StanfordNLP and Smile) as well. Both's results are deterministic.

**Comment by bwaldvogel** [comment]
Can you upload the datasets you are using?
Depending on your platform and compiler, I wouldn’t exclude a slightly different floating point precision/behaviour as an explanation.

**Comment by hrzafer** [comment]
Here is the [link](https://www.dropbox.com/s/9av8o81arolvyh6/diligen.zip?dl=1) A bias term f=1 is added as the last feature.

**Comment by bwaldvogel** [comment]
Assuming you are using the "L1-regularized logistic regression" solver ("`-s 6`") I’ve conducted the following experiment with your dataset:

`$ ./gradlew assemble`
`$ java -cp build/classes/main de.bwaldvogel.liblinear.Train -s 6 -p 0.3 train.libsvm model`
```
iter   1  #CD cycles 1
iter   2  #CD cycles 1
iter   3  #CD cycles 1
iter   4  #CD cycles 1
iter   5  #CD cycles 3
iter   6  #CD cycles 1
=========================
optimization finished, #iter = 6
Objective value = 14871.7
#nonzeros/#features = 6455/181257
```

Whenever I repeat it, I get the exact same output and model file.
What are you doing differently?
Note: When you are training programmatically, you need to call `Linear.resetRandom()` if you want to get completely deterministic results.

**Comment by hrzafer** [comment]
I had also suspected that some kind of resetting mechanism was missing. I didn't know about the `Linear.resetRandom()` method which resolved the problem. Thanks.
