### ISSUE TITLE
InvalidInputDataException: indices must be sorted in ascending order (line 479)

### ISSUE THREAD

**Issue by sygel** [bwaldvogel/liblinear-java#23]
liblinear has problems reading libsvm formatted files which use index 0

Is there a reason for this or is it just a bug?
If it is a bug could you change line 307 in the Train class to
int indexBefore = -1;

**Comment by bwaldvogel** [comment]
From the README:

> About the data format, please check the README file of LIBSVM. Note that feature index must start from 1 (but not 0).

I’ll improve the exception message.
