### ISSUE TITLE
Bias term is added by default

### ISSUE THREAD

**Issue by hrzafer** [bwaldvogel/liblinear-java#28]
The following code will result a `Model` object where `model.nr_feature` = `n-1` even if the number of features in the dataset is `n` excluding the `bias` term.

```Problem problem = new Problem();
problem.l = l
problem.n = n
problem.x = x
problem.y = y
...
Model model = Linear.train(problem, parameter);
```
This is because in the above code, `bias` term is added implicitly (default value for `problem.bias` is `0`) and in `Linear.train()` there is a line `if (prob.bias >= 0) model.nr_feature = n - 1;`. To avoid this we can change line `problem.n = n` as `problem.n = n+1`. But the Java Api documentation is misleading and CLI documentation says the default value for `bias` is `-1` which makes one think that it is also the case for programmatic access.

**Comment by Damiox** [comment]
I've also noticed this while exploring the model file created through `Model.save(...)`. I'm trying to understand if leaving bias as `0` could be affecting my classification results. My problem parameter is defined as: `new Parameter(SolverType.L2R_LR, 1.0, 0.01)`

**Comment by bwaldvogel** [comment]
Thanks for reporting. This is definitely a surprising/undocumented behavior and thus I changed it in 80966110a59a3d48653dec7e17e60c08bd23e0b2.
