### ISSUE TITLE
Bias parameter not used in Linear.predictValues()

### ISSUE THREAD

**Issue by tomas-milata** [bwaldvogel/liblinear-java#29]
I am using a logistic regression model with 2 features and a bias.

I would expect the score to be calculated as

```
w1*x1 + w2*x2 + bias
```

but looking at https://github.com/bwaldvogel/liblinear-java/blob/99518885860ad5f88f7582c3fb491607352b6dc7/src/main/java/de/bwaldvogel/liblinear/Linear.java#L503 it seems like the `bias` parameter is never added to `dec_values`.

Am I right to think the `bias` parameter should contribute to the score or is my understanding incorrect?

**Comment by zenogantner** [comment]
Hello,

Have a look at this line here:
```
if (model.bias >= 0)
            n = model.nr_feature + 1;
```

This leads to the bias term being included in the weight vector.

You can double check for your case by writing out your weight vector and see whether it has 2 or 3 entries. I would guess it will have 3.

The code is a bit confusing to Java developers because it is ported from C++, and kept very similar to the original source for maintainability reasons.

**Comment by tomas-milata** [comment]
Hello,

thanks for your quick reply.

Maybe I should describe my use case a little more.

I'm using `liblinear-java` only for inference, doing training separately (not using liblinear for training).
My trained model uses 2 features and has e.g. coefficients `w1=1` `w2=-2` and `bias=3`.

I'm loading the model from a file that I construct manually and using `Linear.predictProbability()` directly for inference directly (not using the CLI).

I'd like my prediction score to be calculated as `w1*x1 + w2*x2 + bias`. For that, I'd expect the right way to write the model file to be

```
solver_type L2R_LR
nr_class 2
label 1 0 
nr_feature 2
bias 3.0000000000000000 
w
1.0000000000000000 
-2.0000000000000000 
```

and to run the inference with an array of 2 `FeatureNode`s.

But that doesn't seem to add the `bias` to the sum. Yes, due to 

```
if (model.bias >= 0)
            n = model.nr_feature + 1;
```

, `n` is increased, but `bias` does not seem to be added to the `w` vector.

I managed to get expected results by modifying to model from above to

```
solver_type L2R_LR
nr_class 2
label 1 0 
nr_feature 3
bias -1
w
1.0000000000000000 
-2.0000000000000000 
3.0000000000000000 
```

and then calling `Linear.predictProbability()` with an array of 3 `FeatureNode`s (the last one with value of `1`). I basically replaced the bias constant with a 3rd feature with a constant value of `1` and `w3=<original bias>`.

Am I misunderstanding something about how the `bias` parameter is supposed to work?

**Comment by bwaldvogel** [comment]
@tomas-milata: Could you do me a favor and check if the Java implementation¹ does exactly the same thing as the C++ version? 

If yes, please file this issue in https://github.com/cjlin1/liblinear.

_¹ the part of the code that is relevant for this issue_

**Comment by tomas-milata** [comment]
Hi! Sorry, I've found a workaround for this, my project is finished and don't have capacity to check this.
