### ISSUE TITLE
Linear's global RNG makes it difficult to reproduce models or track concurrent executions

### ISSUE THREAD

**Issue by Craigacp** [bwaldvogel/liblinear-java#40]
We use liblinear-java in [Tribuo](https://github.com/oracle/tribuo), and it’s working very well. We’re adding a reproducibility package to Tribuo to rebuild Tribuo models from the provenance metadata they carry, and as part of the tests for that package I noticed that liblinear-java has a global RNG that causes some of the algorithms to not produce bit-wise exact reproductions when executed on the same inputs. In general Tribuo tracks all RNG state and manages it to ensure that concurrent training runs use independently tracked streams of random numbers for provenance purposes, and the global shared state in liblinear-java means we can’t effectively track it and so we’ll have to enforce sequential use of liblinear-java via synchronization and consistently reset the RNG to a known state.

Is it possible to move the static `random` instance in `Linear` into `Problem` as an instance field? To preserve the original behaviour it could initialize itself to a Random instance using `DEFAULT_RANDOM_SEED`, or the code could be modified so it defaults to the global RNG if no instance RNG is present in the `Problem`. The first option would basically just be a find/replace on `random` with `prob.random`, along with adding the extra field to `Problem` (I think it touches approximately 9 lines). The second option would be a little more involved as it requires guards on the 8 uses of `random` and thus would slightly increase divergence from the C++ liblinear, so might not be as desirable from a maintainability perspective. However it would preserve the existing behaviour exactly for users who don’t set the `random` field on `Problem`. We’d be happy to contribute either patch if you’d accept it.

**Comment by bwaldvogel** [comment]
I think that `Problem` would not be the right place to move `random` to. `Problem` describes the dataset.
However, I think that `Parameter` would be a good fit since it describes/configures how to solve the problem. The PRNG is actually one such parameter.

I’ve drafted a proposal in bb15308d497b9fa6053266b41afa35858025da51 and I would appreciate to get feedback on it.

**Comment by Craigacp** [comment]
That update looks good. I agree `Parameter` is a better location for it, I suggested `Problem` as it didn't require updating the constructors in `SolverMCSVM_CS`, but `Parameter` is a better fit if the constructor change is ok.

**Comment by bwaldvogel** [comment]
Ok, thanks for the review. I’ve pushed the change to master and it will be part of the next release.

**Comment by Craigacp** [comment]
That's great, thanks.

**Comment by bwaldvogel** [comment]
This change is now released via version `2.44`.

**Comment by Craigacp** [comment]
Thanks, I've made a Tribuo PR based on the new liblinear-java version which clears up all the locking we had introduced. It's much nicer now.
